# Переменуйте файл после в tokens.yml

bot:
  id: id телеграм бота
  hash: хеш телеграм бота
  chat: основной чат (с минусом)
  creator: id создателя (для стафф)
  token: токен бота

# Для NOIP, если DDNS
noip:
  email: ------@yandex.ru
  password: --------
  name: trassert

# Для REG.RU, если DDNS
reg:
  email: -------@yandex.ru
  password: --------

rcon: 
  password: пароль для RCON из тг
  port: 25575
  port_fabric: порт для еще одного сервера

mysql_map:
  host: localhost
  user: trassert
  password: пароль для карты
  database: authy
  table: players

mysql_users:
  host: localhost
  user: trassert
  password: пароль для юзертаблицы
  database: trassert
  table: users

hotmc: токен для хотмс
mcservers: токен для мсерверс
google: токен для ИИ гугл
chattohttp: пароль для C2HTTP